#!/usr/bin/env python3
r"""
_pipeline.py -- H1 R2 Pipeline: Obsidian Papers -> Cloudflare R2

Ingests markdown papers from G:/My Drive/Obsidian/releases/ and uploads them
to Cloudflare R2 qnfo/papers/[slug].md with metadata extraction, deduplication,
encoding validation, resumability, and a dry-run mode.

Usage:
    python _pipeline.py               # Full upload
    python _pipeline.py --dry-run     # Simulate only, no R2 writes

Dependencies:
    - wrangler_utils.py (in tools/, imported at runtime)
    - charset_normalizer (pip install charset_normalizer) -- optional, falls back to chardet

Author: QWAV Program Agent
Date: 2026-05-28
"""

import argparse
import hashlib
import json
import os
import re
import sys
import time
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ── Path setup ────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
TOOLS_DIR = SCRIPT_DIR / "tools"
sys.path.insert(0, str(TOOLS_DIR))

from wrangler_utils import run_wrangler, upload_to_r2, get_r2_object  # noqa: E402

# ── Optional: encoding detection ──────────────────────────────────────────────
try:
    import charset_normalizer as charset_detector
    HAS_CHARSET_NORMALIZER = True
except ImportError:
    try:
        import chardet as charset_detector  # type: ignore
        HAS_CHARSET_NORMALIZER = True
    except ImportError:
        charset_detector = None  # type: ignore
        HAS_CHARSET_NORMALIZER = False


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

SOURCE_DIR = Path(r"G:\My Drive\Obsidian\releases")
R2_BUCKET = "qnfo"
R2_PAPERS_PREFIX = "papers"
R2_ARCHIVE_PREFIX = "papers/archive"
ARCHIVE_CUTOFF_YEAR = 2025  # Papers before this year go to archive
STATE_FILE = SCRIPT_DIR / "_pipeline_state.json"
ERROR_LOG = SCRIPT_DIR / "_pipeline_errors.log"
SLUG_MAX_LEN = 80

# Files to skip (indices, autogenerated, non-papers)
SKIP_PATTERNS = [
    re.compile(r"^_"),                # _releases.md, _2025.md, etc.
    re.compile(r"Zoottelkeeper"),     # Autogenerated index files
]

# Regex for detecting version-number-only titles (1.0, 0.9.1, 2.3.5, 0.1.4.3, etc.)
VERSION_NUMBER_RE = re.compile(r'^"?[\d]+(?:\.[\d]+)+"?$')

# Regex for extracting date from various formats
DATE_YMD_RE = re.compile(r'(\d{4})[-/](\d{2})[-/](\d{2})')

# Rich console helpers
class Style:
    """Minimal ANSI styling for Windows / cross-platform compatibility."""
    HEADER = '\033[1;36m'
    OK = '\033[1;32m'
    WARN = '\033[1;33m'
    FAIL = '\033[1;31m'
    DIM = '\033[2m'
    BOLD = '\033[1m'
    RESET = '\033[0m'

    @staticmethod
    def supports_color() -> bool:
        return sys.stdout.isatty() and os.name != 'nt' or 'WT_SESSION' in os.environ


if not Style.supports_color():
    for attr in dir(Style):
        if not attr.startswith('_') and attr.isupper():
            setattr(Style, attr, '')


# ═══════════════════════════════════════════════════════════════════════════════
# CORE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def find_papers(source_dir: Path) -> List[Path]:
    """
    Recursively find all .md files in source_dir, excluding skip patterns.

    Returns:
        List of absolute Path objects sorted by path.
    """
    papers: List[Path] = []
    for root, dirs, files in os.walk(source_dir):
        for fname in files:
            if not fname.endswith('.md'):
                continue
            full_path = Path(root) / fname
            rel = full_path.relative_to(source_dir)

            # Skip index/autogenerated files
            should_skip = False
            for pat in SKIP_PATTERNS:
                if pat.search(fname) or pat.search(str(rel.parts[0])):
                    should_skip = True
                    break
            if should_skip:
                continue

            papers.append(full_path)

    papers.sort()
    return papers


def read_file_raw(filepath: Path) -> Tuple[Optional[str], Optional[str]]:
    """
    Read a file, attempting UTF-8 first, then detecting encoding.

    Returns:
        (content, encoding_used) or (None, None) on failure.
        encoding_used is 'utf-8', 'cp1252', 'detected:<enc>', etc.
    """
    # Try UTF-8 first (most common for these papers)
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return f.read(), 'utf-8'
    except UnicodeDecodeError:
        pass

    # Try charset detection
    if HAS_CHARSET_NORMALIZER and charset_detector is not None:
        try:
            with open(filepath, 'rb') as f:
                raw_bytes = f.read()
            # charset_normalizer gives the most likely encoding
            if hasattr(charset_detector, 'from_bytes'):
                result = charset_detector.from_bytes(raw_bytes)
                best = result.best()
                if best and best.encoding:
                    detected = best.encoding
                    return raw_bytes.decode(detected, errors='replace'), f'detected:{detected}'
        except Exception:
            pass

    # Fallback: CP1252 (common Windows encoding) with error replacement
    try:
        with open(filepath, 'r', encoding='cp1252', errors='replace') as f:
            return f.read(), 'cp1252-fallback'
    except Exception:
        pass

    # Last resort: latin-1 (never fails, but may be wrong)
    try:
        with open(filepath, 'r', encoding='latin-1', errors='replace') as f:
            return f.read(), 'latin-1-fallback'
    except Exception:
        return None, None


def validate_and_convert_utf8(filepath: Path) -> Tuple[Optional[str], bool]:
    """
    Read file and ensure UTF-8 content. Logs conversion if needed.

    Returns:
        (utf8_content, was_converted)
        was_converted is True if encoding was fixed.
    """
    content, encoding = read_file_raw(filepath)
    if content is None:
        return None, False

    if encoding in ('utf-8',):
        # Check if content already validates cleanly as UTF-8
        return content, False

    # Content was converted — re-encode to pure UTF-8 bytes and decode back
    # to verify the content is valid UTF-8
    try:
        content.encode('utf-8')
    except UnicodeEncodeError:
        content = content.encode('utf-8', errors='replace').decode('utf-8')

    return content, True


def extract_frontmatter(content: str) -> Tuple[Dict[str, Any], str]:
    """
    Extract YAML-style frontmatter and return (metadata_dict, body_after_fm).

    Parses Obsidian-style YAML frontmatter delimited by ---.
    Handles multi-line values (Obsidian aliases format) and edge cases.

    Returns:
        (metadata_dict, body_content_after_frontmatter)
    """
    metadata: Dict[str, Any] = {}
    body = content

    if not content.startswith('---'):
        return metadata, body

    lines = content.split('\n')
    if len(lines) < 2:
        return metadata, body

    # Find closing ---
    close_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == '---':
            close_idx = i
            break

    if close_idx is None:
        return metadata, body

    fm_lines = lines[1:close_idx]
    body = '\n'.join(lines[close_idx + 1:])

    # Parse YAML-like key: value pairs
    # Handle multi-line values (Obsidian format where value is indented on next line)
    current_key: Optional[str] = None
    current_value: List[str] = []

    def _flush_key() -> None:
        nonlocal current_key, current_value
        if current_key and current_value:
            val = '\n'.join(current_value).strip().strip('"').strip("'")
            # Handle Obsidian aliases list format
            if current_key == 'aliases':
                alias_set: List[str] = []
                for line in current_value:
                    # Check for inline bracket format: [item1, item2, item3]
                    bracket_match = re.match(r'^\s*\[(.+)\]\s*$', line)
                    if bracket_match:
                        items = re.split(r',\s*', bracket_match.group(1))
                        for item in items:
                            cleaned = item.strip().strip('"').strip("'")
                            if cleaned:
                                alias_set.append(cleaned)
                        continue
                    # Try - "value" format
                    m = re.search(r'"([^"]*)"', line)
                    if m:
                        alias_set.append(m.group(1))
                    else:
                        stripped = line.strip().lstrip('-').strip().strip('"').strip("'")
                        if stripped:
                            alias_set.append(stripped)
                metadata[current_key] = alias_set
            else:
                metadata[current_key] = val
        elif current_key is not None and not current_value:
            metadata[current_key] = ''
        current_key = None
        current_value = []

    for line in fm_lines:
        # Check for key: value pattern
        kv_match = re.match(r'^(\w[\w-]*):\s*(.*)', line)
        if kv_match:
            _flush_key()
            key = kv_match.group(1)
            value_part = kv_match.group(2).rstrip()
            current_key = key
            if value_part:
                current_value = [value_part]
            else:
                current_value = []
        elif current_key is not None:
            # Continuation line for multi-line value
            current_value.append(line)
        # else: ignore lines before first key

    _flush_key()

    return metadata, body


def clean_title(raw: str) -> str:
    """
    Clean a raw title string by stripping markdown formatting, brackets,
    and Obsidian note-prefix patterns.

    Handles:
    - **bold** markers
    - [prefix] bracketed prefixes (Obsidian note-title patterns)
    - Leading/trailing brackets
    - Extra whitespace
    """
    cleaned = raw.strip()

    # Strip markdown bold/italic markers
    cleaned = re.sub(r'\*\*(.+?)\*\*', r'\1', cleaned)
    cleaned = re.sub(r'\*(.+?)\*', r'\1', cleaned)
    cleaned = re.sub(r'__(.+?)__', r'\1', cleaned)
    cleaned = re.sub(r'_(.+?)_', r'\1', cleaned)

    # Strip leading "[prefix, ...] " patterns (Obsidian aliases/note prefixes)
    # Example: "[5I, 1. Background, 5 I] Actual Title" -> "Actual Title"
    cleaned = re.sub(r'^\[[^\]]+\]\s+', '', cleaned)

    # If the whole title is wrapped in brackets, unwrap
    if cleaned.startswith('[') and cleaned.endswith(']') and cleaned.count('[') == 1:
        cleaned = cleaned[1:-1].strip()

    # Strip leading/trailing quotes
    cleaned = cleaned.strip('\'"')

    # Collapse whitespace
    cleaned = re.sub(r'\s+', ' ', cleaned)

    return cleaned.strip()


def extract_title(metadata: Dict[str, Any], body: str, filename: str) -> str:
    """
    Extract paper title with fallback chain:
    1. YAML 'title' field (if not a version number like "1.0")
    2. First H1 heading (# Title) in body
    3. Filename without extension

    Returns cleaned title string.
    """
    # 1. Try YAML title
    yaml_title = metadata.get('title', '')
    yaml_title_clean = str(yaml_title).strip().strip('"').strip("'")

    # Determine if the YAML title is usable
    yaml_is_good = bool(
        yaml_title_clean and
        not VERSION_NUMBER_RE.match(yaml_title_clean) and
        len(yaml_title_clean) >= 5  # Too short to be meaningful
    )

    if yaml_is_good:
        return clean_title(yaml_title_clean)

    # YAML title is missing, version-only, or too short — try aliases
    aliases = metadata.get('aliases', [])
    if isinstance(aliases, list):
        for alias in aliases:
            alias_str = str(alias).strip().strip('"').strip("'")
            # Skip aliases that are clearly not titles
            if ',' in alias_str:
                continue  # Comma-separated = tag list
            if '/' in alias_str or '\\' in alias_str:
                continue  # Path-like (Obsidian internal links)
            if '[[' in alias_str or ']]' in alias_str:
                continue  # Wiki-link syntax
            if len(alias_str) <= 3:
                continue  # Too short
            if len(alias_str) > 200:
                continue  # Suspiciously long
            if VERSION_NUMBER_RE.match(alias_str):
                continue
            if 'SYSTEM OUTPUT' in alias_str.upper():
                continue
            # Found a usable alias title
            return clean_title(alias_str)

    # If original YAML title was somewhat usable (just short), return it
    if yaml_title_clean:
        return clean_title(yaml_title_clean)

    # 2. Try first H1 heading
    h1_match = re.search(r'^#\s+(.+?)(?:\s*\{[^}]*\})?\s*$', body, re.MULTILINE)
    if h1_match:
        return clean_title(h1_match.group(1))

    # 3. Fallback to filename
    return clean_title(Path(filename).stem)


def extract_date(metadata: Dict[str, Any], body: str, filepath: Path) -> Optional[str]:
    """
    Extract publication date in YYYY-MM-DD format from multiple sources:
    1. YAML 'date' field
    2. YAML 'modified' field (take date portion)
    3. Body inline metadata (**Date:**, **Publication Date:**)
    4. Parse from directory path or filename

    Returns date string or None.
    """
    # 1. YAML date field
    yaml_date = metadata.get('date', '')
    date_match = DATE_YMD_RE.search(str(yaml_date))
    if date_match:
        return f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}"

    # 2. YAML modified field
    modified = metadata.get('modified', '')
    if modified:
        # Try ISO 8601: 2025-12-01T06:32:12Z
        iso_match = re.match(r'(\d{4}-\d{2}-\d{2})[T ]', str(modified))
        if iso_match:
            return iso_match.group(1)

    # 3. Body inline metadata
    for pattern in [
        r'\*\*Publication Date:\*\*\s*(\d{4}-\d{2}-\d{2})',
        r'\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})',
        r'\*\*Publication Date:\*\*\s*(\d{4})[-/](\d{2})[-/](\d{2})',
        r'\*\*Date:\*\*\s*(\d{4})[-/](\d{2})[-/](\d{2})',
    ]:
        m = re.search(pattern, body, re.IGNORECASE)
        if m:
            groups = m.groups()
            if len(groups) == 3:
                return f"{groups[0]}-{groups[1]}-{groups[2]}"
            elif len(groups) == 1:
                return groups[0]

    # 4. Parse from directory structure: releases/YYYY/MM/...
    try:
        rel = filepath.relative_to(SOURCE_DIR)
        parts = rel.parts
        if len(parts) >= 2 and parts[0].isdigit():
            year = parts[0]
            month = parts[1] if len(parts) >= 2 and parts[1].isdigit() else '01'
            return f"{year}-{month.zfill(2)}-01"
    except (ValueError, IndexError):
        pass

    return None


def extract_keywords(metadata: Dict[str, Any], body: str) -> List[str]:
    """
    Extract keywords from multiple sources:
    1. YAML 'keywords' or 'tags' field
    2. Inline **Keywords:** in body
    3. Inline **Keywords** in body (no colon)

    Returns list of keyword strings.
    """
    # 1. YAML keywords
    yaml_kw = metadata.get('keywords', '')
    if yaml_kw and isinstance(yaml_kw, str):
        # Could be comma-separated, semicolon-separated, or YAML list string
        kws = re.split(r'[,;]\s*', yaml_kw)
        kws = [k.strip().strip('"').strip("'") for k in kws if k.strip()]
        if kws:
            return kws

    # 2. YAML tags
    yaml_tags = metadata.get('tags', '')
    if yaml_tags and isinstance(yaml_tags, str):
        kws = re.split(r'[,;]\s*', yaml_tags)
        kws = [k.strip().strip('"').strip("'") for k in kws if k.strip()]
        if kws:
            return kws

    # 3. Body inline **Keywords:** or **Keywords**
    kw_patterns = [
        r'\*\*Keywords?\*\*[:\s]+(.+?)(?:\n|$)',
        r'\*\*Keywords?\*\*:\s*(.+?)(?:\n\n|\n\*\*|\Z)',
        r'Keywords?[:\s]+(.+?)(?:\n|$)',
    ]
    for pat in kw_patterns:
        m = re.search(pat, body, re.IGNORECASE | re.DOTALL)
        if m:
            kw_text = m.group(1).strip()
            # Split on common separators
            kws = re.split(r'[,;]\s*', kw_text)
            kws = [k.strip().rstrip('.') for k in kws if k.strip()]
            if kws:
                return kws

    return []


def extract_abstract(body: str) -> str:
    """
    Extract first meaningful paragraph after frontmatter as abstract.
    Skips headings, metadata lines, and horizontal rules.

    Returns up to 2000 chars of abstract text.
    """
    lines = body.split('\n')
    abstract_lines: List[str] = []
    in_abstract = False
    found_text = False

    for line in lines:
        stripped = line.strip()

        # Skip blank lines before abstract starts
        if not in_abstract:
            if not stripped:
                continue
            # Skip headings, metadata lines, horizontal rules
            if (stripped.startswith('#') or
                stripped.startswith('**') or
                stripped.startswith('---') or
                stripped.startswith('>') or
                stripped.startswith('![')):
                continue
            # Start of actual content
            in_abstract = True

        if in_abstract:
            # Stop at next heading or horizontal rule
            if stripped.startswith('##') or stripped == '---':
                break
            if stripped.startswith('**') and found_text:
                # Metadata line in middle of abstract (skip)
                continue
            if stripped:
                abstract_lines.append(stripped)
                found_text = True
            elif abstract_lines:
                # Blank line after some content — include it as paragraph break
                abstract_lines.append('')
            # If we have enough, stop
            joined = ' '.join(abstract_lines)
            if len(joined) > 2000:
                break

    abstract = ' '.join(abstract_lines).strip()
    # Clean up double spaces
    abstract = re.sub(r'\s+', ' ', abstract)

    # If abstract starts with "**Abstract**" or similar, strip that prefix
    abstract = re.sub(r'^\*\*Abstract\*\*[:\s]*', '', abstract).strip()

    return abstract[:2000]


def generate_slug(title: str) -> str:
    """
    Generate URL-safe slug from title.
    - Lowercase
    - Replace non-alphanumeric with hyphens
    - Collapse multiple hyphens
    - Trim to max length
    - Strip leading/trailing hyphens
    """
    slug = title.lower()
    # Replace any non-alphanumeric (except hyphens) with hyphen
    slug = re.sub(r'[^a-z0-9]+', '-', slug)
    # Collapse multiple hyphens
    slug = re.sub(r'-+', '-', slug)
    # Trim to max length
    if len(slug) > SLUG_MAX_LEN:
        # Try to cut at word boundary
        slug = slug[:SLUG_MAX_LEN].rstrip('-')
        # If we cut mid-word, trim back to last hyphen
        last_hyphen = slug.rfind('-')
        if last_hyphen > SLUG_MAX_LEN // 2:
            slug = slug[:last_hyphen]
    # Strip leading/trailing hyphens
    slug = slug.strip('-')
    # If slug is empty (rare edge case), use hash
    if not slug:
        slug = f"paper-{hashlib.md5(title.encode()).hexdigest()[:8]}"
    return slug


def normalize_title(title: str) -> str:
    """Normalize title for deduplication comparison."""
    return re.sub(r'[^a-z0-9]', '', title.lower())


def paper_exists_in_r2(r2_path: str, dry_run: bool = False) -> bool:
    """
    Check if a paper already exists in R2.

    Args:
        r2_path: Full R2 key (e.g., 'papers/my-slug.md')
        dry_run: If True, always returns False (simulate fresh upload)
    """
    if dry_run:
        return False

    result = run_wrangler(
        ['r2', 'object', 'get', f'{R2_BUCKET}/{r2_path}', '--remote', '--head'],
        timeout=15,
    )
    return result.returncode == 0


def process_paper(
    filepath: Path,
    dry_run: bool = False,
    seen_titles: Optional[set] = None,
    args_resume: bool = False,
    args_force: bool = False,
) -> Dict[str, Any]:
    """
    Process a single paper: read, extract metadata, generate slug, upload to R2.

    Args:
        filepath: Absolute path to .md file
        dry_run: If True, simulate but don't actually upload
        seen_titles: Set of normalized titles for dedup
        args_resume: If True, check R2 before uploading (skip existing)
        args_force: If True, re-upload even if already in R2

    Returns:
        Dict with status and metadata about the processing result.
    """
    if seen_titles is None:
        seen_titles = set()

    result: Dict[str, Any] = {
        'status': 'unknown',
        'file': str(filepath),
        'slug': None,
        'title': None,
        'date': None,
        'keywords': [],
        'encoding_fixed': False,
        'r2_path': None,
        'error': None,
    }

    # 1. Read and validate encoding
    content, was_converted = validate_and_convert_utf8(filepath)
    if content is None:
        result['status'] = 'error'
        result['error'] = 'Failed to read file'
        return result
    result['encoding_fixed'] = was_converted

    # 2. Extract frontmatter
    metadata, body = extract_frontmatter(content)

    # 3. Extract title
    title = extract_title(metadata, body, filepath.name)
    result['title'] = title

    # 4. Dedup check
    normalized = normalize_title(title)
    if normalized in seen_titles:
        result['status'] = 'skipped'
        result['error'] = f'Duplicate title: {title}'
        return result
    seen_titles.add(normalized)

    # 5. Generate slug
    slug = generate_slug(title)
    result['slug'] = slug

    # 6. Extract date and determine archive path
    date = extract_date(metadata, body, filepath)
    result['date'] = date

    if date:
        year = int(date[:4])
    else:
        # Try to infer year from directory structure
        try:
            rel = filepath.relative_to(SOURCE_DIR)
            parts = rel.parts
            if parts[0].isdigit():
                year = int(parts[0])
                date = f"{year}-01-01"  # Default
            else:
                year = ARCHIVE_CUTOFF_YEAR  # Assume current
                date = f"{year}-01-01"
        except (ValueError, IndexError):
            year = ARCHIVE_CUTOFF_YEAR
            date = f"{year}-01-01"

    result['date'] = date

    # Determine R2 path
    if year < ARCHIVE_CUTOFF_YEAR:
        r2_path = f"{R2_ARCHIVE_PREFIX}/{year}/{slug}.md"
    else:
        r2_path = f"{R2_PAPERS_PREFIX}/{slug}.md"
    result['r2_path'] = r2_path

    # 7. Extract keywords
    keywords = extract_keywords(metadata, body)
    result['keywords'] = keywords

    # 8. Extract abstract
    abstract = extract_abstract(body)

    # 9. Check if already uploaded (resumability) — only when --resume
    if args_resume and not args_force and paper_exists_in_r2(r2_path, dry_run):
        result['status'] = 'already_uploaded'
        return result

    # 10. Build enriched content with metadata header
    # Add YAML frontmatter with extracted metadata for downstream consumers
    enriched_lines = ['---']
    enriched_lines.append(f'title: "{title}"')
    if date:
        enriched_lines.append(f'date: {date}')
    if keywords:
        kw_str = ', '.join(keywords)
        enriched_lines.append(f'keywords: [{kw_str}]')
    enriched_lines.append(f'slug: {slug}')
    enriched_lines.append(f'source: {filepath.relative_to(SOURCE_DIR)}')
    if abstract:
        # Truncate for frontmatter readability
        enriched_lines.append(f'abstract: >')
        for abstract_line in abstract[:500].split('\n'):
            enriched_lines.append(f'  {abstract_line.strip()}')
    enriched_lines.append('---')
    enriched_lines.append('')
    enriched_lines.append(content)

    enriched_content = '\n'.join(enriched_lines)

    # 11. Upload
    if dry_run:
        result['status'] = 'dry_run'
        return result

    # Write to temp file and upload
    tmp_path = SCRIPT_DIR / f"_tmp_{slug}.md"
    try:
        with open(tmp_path, 'w', encoding='utf-8') as f:
            f.write(enriched_content)

        success = upload_to_r2(r2_path, str(tmp_path), bucket=R2_BUCKET, timeout=120)

        if success:
            result['status'] = 'uploaded'
        else:
            result['status'] = 'error'
            result['error'] = 'R2 upload failed'
    except Exception as e:
        result['status'] = 'error'
        result['error'] = str(e)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()

    return result


def load_state() -> Dict[str, Any]:
    """Load pipeline state for resumability."""
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            pass
    return {'seen_titles': [], 'uploaded_slugs': [], 'last_run': None}


def save_state(seen_titles: set, uploaded_slugs: List[str]) -> None:
    """Save pipeline state for resumability."""
    state = {
        'seen_titles': sorted(seen_titles),
        'uploaded_slugs': uploaded_slugs,
        'last_run': datetime.now().isoformat(),
        'total_seen': len(seen_titles),
    }
    with open(STATE_FILE, 'w', encoding='utf-8') as f:
        json.dump(state, f, indent=2)


def log_error(filepath: str, error: str) -> None:
    """Append an error to the error log."""
    timestamp = datetime.now().isoformat()
    with open(ERROR_LOG, 'a', encoding='utf-8') as f:
        f.write(f"[{timestamp}] {filepath}: {error}\n")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="H1 R2 Pipeline — Ingest Obsidian papers to Cloudflare R2",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python _pipeline.py                 # Full upload
  python _pipeline.py --dry-run       # Simulate, no R2 writes
  python _pipeline.py --limit 10      # Process only first 10 papers
        """,
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help='Simulate pipeline without uploading to R2'
    )
    parser.add_argument(
        '--limit', type=int, default=0,
        help='Limit number of papers to process (0 = all)'
    )
    parser.add_argument(
        '--resume', action='store_true',
        help='Skip already-uploaded papers (uses R2 existence check)'
    )
    parser.add_argument(
        '--fresh', action='store_true',
        help='Clear previous state and start fresh (ignore saved dedup data)'
    )
    parser.add_argument(
        '--force', action='store_true',
        help='Force re-upload even if paper already exists in R2'
    )

    args = parser.parse_args()

    # ── Header ────────────────────────────────────────────────────────────
    print(f"{Style.HEADER}{'='*70}{Style.RESET}")
    print(f"{Style.HEADER}  H1 R2 PIPELINE — Obsidian Papers → Cloudflare R2{Style.RESET}")
    print(f"{Style.HEADER}{'='*70}{Style.RESET}")
    print(f"  Source: {SOURCE_DIR}")
    print(f"  Target: {R2_BUCKET}/{R2_PAPERS_PREFIX}/[slug].md")
    print(f"  Dry run: {args.dry_run}")
    print(f"  Force: {args.force}")
    print(f"  Resume: {args.resume}")
    print()

    # ── Discover papers ───────────────────────────────────────────────────
    print(f"{Style.DIM}Discovering papers...{Style.RESET}")
    papers = find_papers(SOURCE_DIR)
    total_found = len(papers)
    print(f"  Found: {Style.BOLD}{total_found}{Style.RESET} markdown files")
    if args.limit and args.limit < total_found:
        papers = papers[:args.limit]
        print(f"  Processing (limit): {Style.BOLD}{len(papers)}{Style.RESET}")
    print()

    if not papers:
        print(f"{Style.WARN}No papers found. Exiting.{Style.RESET}")
        return

    # ── Load state for dedup tracking ─────────────────────────────────────
    if args.fresh:
        seen_titles: set = set()
        uploaded_slugs: List[str] = []
        print(f"  {Style.DIM}Fresh run — clearing previous state{Style.RESET}")
    else:
        state = load_state()
        seen_titles: set = set(state.get('seen_titles', []))
        uploaded_slugs: List[str] = state.get('uploaded_slugs', [])
        if seen_titles:
            print(f"  {Style.DIM}Loaded {len(seen_titles)} previously seen titles from state{Style.RESET}")
    print()

    # ── Process papers ────────────────────────────────────────────────────
    stats = Counter()
    progress = 0
    start_time = time.time()

    for i, filepath in enumerate(papers, 1):
        progress = i
        rel_path = filepath.relative_to(SOURCE_DIR)

        # Progress indicator
        pct = (i / len(papers)) * 100
        bar_len = 30
        filled = int(bar_len * i / len(papers))
        bar = '█' * filled + '░' * (bar_len - filled)

        result = process_paper(
            filepath,
            dry_run=args.dry_run,
            seen_titles=seen_titles,
            args_resume=args.resume,
            args_force=args.force,
        )

        # Update stats
        stats[result['status']] += 1

        # Status indicator
        status_icon = {
            'uploaded': f'{Style.OK}✓{Style.RESET}',
            'dry_run': f'{Style.DIM}○{Style.RESET}',
            'already_uploaded': f'{Style.DIM}●{Style.RESET}',
            'skipped': f'{Style.WARN}⊘{Style.RESET}',
            'error': f'{Style.FAIL}✗{Style.RESET}',
        }.get(result['status'], f'{Style.FAIL}?{Style.RESET}')

        # Build compact output line
        title_display = (result.get('title') or '?')[:55]
        slug_display = (result.get('slug') or '?')[:30]
        enc_flag = ' [ENC]' if result.get('encoding_fixed') else ''

        print(f"  [{bar}] {status_icon} "
              f"{Style.DIM}{i:3d}/{len(papers)}{Style.RESET} "
              f"{title_display:<56} "
              f"{Style.DIM}{slug_display}{enc_flag}{Style.RESET}")

        # Log errors
        if result['status'] == 'error' and result.get('error'):
            log_error(str(filepath), result['error'])

        # Track uploaded slugs
        if result['status'] in ('uploaded',):
            slug = result.get('slug')
            if slug:
                uploaded_slugs.append(slug)

        # Save state periodically (every 50 papers)
        if i % 50 == 0:
            save_state(seen_titles, uploaded_slugs)

    # ── Final state save ──────────────────────────────────────────────────
    save_state(seen_titles, uploaded_slugs)

    elapsed = time.time() - start_time

    # ── Summary ───────────────────────────────────────────────────────────
    print()
    print(f"{Style.HEADER}{'='*70}{Style.RESET}")
    print(f"{Style.HEADER}  PIPELINE COMPLETE{Style.RESET}")
    print(f"{Style.HEADER}{'='*70}{Style.RESET}")
    print(f"  Total found:     {stats['uploaded'] + stats['dry_run'] + stats['already_uploaded'] + stats['skipped'] + stats['error']:>5d}")
    print(f"  {Style.OK}Uploaded:{Style.RESET}        {stats['uploaded']:>5d}")
    if stats['dry_run']:
        print(f"  {Style.DIM}Dry run:{Style.RESET}        {stats['dry_run']:>5d}")
    if stats['already_uploaded']:
        print(f"  {Style.DIM}Already in R2:{Style.RESET}  {stats['already_uploaded']:>5d}")
    if stats['skipped']:
        print(f"  {Style.WARN}Skipped (dup):{Style.RESET}   {stats['skipped']:>5d}")
    if stats['error']:
        print(f"  {Style.FAIL}Errors:{Style.RESET}          {stats['error']:>5d}")
    print(f"  Elapsed:         {elapsed:6.1f}s")
    print(f"  State saved:     {STATE_FILE}")
    if stats['error']:
        print(f"  Error log:       {ERROR_LOG}")
    print()
    print(f"  Papers/sec:      {stats['uploaded'] / elapsed if elapsed > 0 else 0:.1f}")


if __name__ == '__main__':
    main()
